<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_012ButterfreeBugFlying</name>
   <tag></tag>
   <elementGuidId>b28581f0-e988-46e9-ac3a-4170189ed97b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div/div/div/div[2]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;#012ButterfreeBugFlying&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>93746401-7ed4-43a5-8d86-0d57f991ee92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative bg-gray-800/70 rounded-lg p-2 cursor-pointer hover:bg-gray-700 transition-all duration-300 border transform animate__animated animate__fadeInUp opacity-100 translate-y-0 border-gray-700</value>
      <webElementGuid>9217a4c3-094d-4d82-ad32-29d0a7b877dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#012ButterfreeBugFlying</value>
      <webElementGuid>38f189d4-0c54-4de8-b84c-d1e6583841a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/main[@class=&quot;mt-16&quot;]/div[@class=&quot;fixed inset-0 top-16 w-full h-[calc(100vh-4rem)] overflow-hidden z-0 flex px-6 py-4 gap-4 rounded-lg&quot;]/div[@class=&quot;flex-1 bg-gray-900/90 backdrop-blur-sm border-r border-gray-700 min-w-0 rounded-lg&quot;]/div[@class=&quot;h-full w-full&quot;]/div[@class=&quot;h-full flex flex-col bg-gray-900/80 border border-gray-700 rounded-lg&quot;]/div[@class=&quot;flex-1 overflow-y-auto p-4 scrollbar-hide&quot;]/div[@class=&quot;grid grid-cols-5 gap-3&quot;]/div[@class=&quot;relative bg-gray-800/70 rounded-lg p-2 cursor-pointer hover:bg-gray-700 transition-all duration-300 border transform animate__animated animate__fadeInUp opacity-100 translate-y-0 border-gray-700&quot;]</value>
      <webElementGuid>f1058e80-5a58-4f64-b1ef-3cca941dd187</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div/div/div[2]/div/div[3]</value>
      <webElementGuid>2a579877-ff3f-4f82-a53f-256eceaa2594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bug'])[2]/following::div[1]</value>
      <webElementGuid>4e91fc3f-61cc-4a9c-943c-f1677723e2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metapod'])[1]/following::div[2]</value>
      <webElementGuid>ffeeb78d-a833-47f7-aa7f-181c43983a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
      <webElementGuid>211e7c21-c28f-49fa-8bb8-bf3e4eea9de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '#012ButterfreeBugFlying' or . = '#012ButterfreeBugFlying')]</value>
      <webElementGuid>b150c930-fc65-4af9-8660-d61fd97db8e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
