<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_019RattataNormal</name>
   <tag></tag>
   <elementGuidId>034fc177-ee01-4dd5-83dd-cd90d391f83e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div/div/div/div[2]/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;#019RattataNormal&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b2d59d53-e0a4-4349-9be7-a1ea85280d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative bg-gray-800/70 rounded-lg p-2 cursor-pointer hover:bg-gray-700 transition-all duration-300 border transform animate__animated animate__fadeInUp opacity-100 translate-y-0 border-gray-700</value>
      <webElementGuid>d771a281-b030-4043-a99d-4c7c71355333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#019RattataNormal</value>
      <webElementGuid>ad328d0f-ee81-4c88-88ea-69945c58ce53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/main[@class=&quot;mt-16&quot;]/div[@class=&quot;fixed inset-0 top-16 w-full h-[calc(100vh-4rem)] overflow-hidden z-0 flex px-6 py-4 gap-4 rounded-lg&quot;]/div[@class=&quot;flex-1 bg-gray-900/90 backdrop-blur-sm border-r border-gray-700 min-w-0 rounded-lg&quot;]/div[@class=&quot;h-full w-full&quot;]/div[@class=&quot;h-full flex flex-col bg-gray-900/80 border border-gray-700 rounded-lg&quot;]/div[@class=&quot;flex-1 overflow-y-auto p-4 scrollbar-hide&quot;]/div[@class=&quot;grid grid-cols-5 gap-3&quot;]/div[@class=&quot;relative bg-gray-800/70 rounded-lg p-2 cursor-pointer hover:bg-gray-700 transition-all duration-300 border transform animate__animated animate__fadeInUp opacity-100 translate-y-0 border-gray-700&quot;]</value>
      <webElementGuid>50aabaa9-6ce6-4288-8c09-fe91d90853cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div/div/div[2]/div/div[4]</value>
      <webElementGuid>1fe9b658-f283-4482-8828-2ea38b262ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flying'])[1]/following::div[1]</value>
      <webElementGuid>4d96def6-cf2c-41cc-9f70-cb265b832ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bug'])[3]/following::div[1]</value>
      <webElementGuid>20c7e61a-ff81-42d3-b271-f4812dfa0f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>5ab83d5a-cc75-49d1-af32-975de4664e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '#019RattataNormal' or . = '#019RattataNormal')]</value>
      <webElementGuid>f0a556fa-046f-468b-959f-cd1e9e397d06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
