<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>13a9cdc4-5cf3-4753-acde-fe0a17033223</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div[3]/div/a[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=main >> internal:role=link >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ba17d76f-ebef-4c26-af32-2ea2592c5cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/src/assets/icons/pokemap_icon.png</value>
      <webElementGuid>41e10001-4a4a-4a7a-8ca1-c9446cde42b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/main[@class=&quot;mt-16&quot;]/div[@class=&quot;min-h-screen pt-20 px-4&quot;]/div[@class=&quot;bg-gray-800/50 shadow-[0px_0px_15px] shadow-gray-600 rounded-2xl p-3 h-fit fixed w-[20%] right-[50px] top-32 pb-6&quot;]/div[@class=&quot;grid grid-cols-2 gap-6&quot;]/a[@class=&quot;w-full h-full rounded-full flex items-center justify-center text-2xl hover:scale-110 transition-transform
                    duration-300 cursor-pointer&quot;]/img[1]</value>
      <webElementGuid>1bb82625-fee7-45d3-aff7-03aba540afd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[3]/div/a[2]/img</value>
      <webElementGuid>f6fe9f58-64d7-47e9-9802-b31741fc9801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>1fcb9e3d-12ae-46b1-894a-ac9210f26d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/src/assets/icons/pokemap_icon.png']</value>
      <webElementGuid>97efa9fa-9284-4b7d-950c-0b225b8392cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[3]/div/a/img</value>
      <webElementGuid>ce995b1e-6d8a-42d5-943e-dd3412e1ad5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>51593d67-1784-4e3d-88b9-b64dfb08dfe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/src/assets/icons/pokedex_icon.png']</value>
      <webElementGuid>3cd19b7e-612a-4e9e-9aa6-20d4e2b3f43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/img</value>
      <webElementGuid>0ce5773e-de26-4aaa-a91e-921e34b937f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
